const modal=document.querySelector("#modal"),form=document.querySelector("#form"),bar=document.querySelector("#bar");let data={type:""},step=0;
const questions=[
()=>({title:"Who is this Ready Pack for?",text:"A few details help make the preparation feel personal.",fields:[["name","First name or nickname","text"],["age","Age (optional)","number"]]}),
()=>({title:"Tell us about the experience.",text:"Keep it simple. You can change this later.",fields:[["when","When is it happening?","text"],["details","What do you already know about the visit or experience?","textarea"]]}),
()=>({title:"What should we prepare for?",text:"Share anything that may make the experience easier to understand or manage.",fields:[["sensory","Sensory needs or things they may find difficult","textarea"],["helps","What usually helps?","textarea"]]}),
()=>({title:"Your Ready Pack is ready.",preview:true})];
function openBuilder(type="Dentist"){data={type};step=0;modal.classList.add("open");modal.setAttribute("aria-hidden","false");render()}
function render(){bar.style.width=((step+1)/questions.length*100)+"%";const q=questions[step]();if(q.preview){renderPack();return}let fields=q.fields.map(([key,label,type])=>'<label for="'+key+'">'+label+'</label>'+(type==="textarea"?'<textarea id="'+key+'" data-key="'+key+'" placeholder="'+placeholder(key)+'">'+esc(data[key]||"")+'</textarea>':'<input id="'+key+'" data-key="'+key+'" type="'+type+'" value="'+esc(data[key]||"")+'" placeholder="'+placeholder(key)+'">')).join("");form.innerHTML='<div class="question"><span class="badge">'+esc(data.type)+'</span><h2>'+q.title+'</h2><p>'+q.text+'</p>'+fields+'<div class="form-actions">'+(step?'<button class="secondary" data-back>← Back</button>':'<span></span>')+'<button class="primary" data-next>Continue →</button></div></div>';bind()}
function placeholder(k){return {name:"Alex",age:"8",when:"Saturday morning",details:"A routine cleaning at a new dentist office.",sensory:"Loud sounds, bright lights, waiting, things near the mouth.",helps:"Headphones, a countdown, short directions, and knowing what happens next."}[k]||""}
function renderPack(){const n=esc(data.name||"My");const isDentist=data.type==="Dentist";const steps=isDentist?[
["🚗","I travel to the dentist","I may go by car, bus, or another way. I can bring something that helps me feel comfortable."],
["🏢","I arrive and check in","We tell the front desk we are here. I may need to wait before it is my turn."],
["⏳","I wait for my turn","Waiting can be hard. I can use a preferred activity or another support while I wait."],
["👋","I meet the dental team","A dental team member may talk with me and explain what will happen next."],
["🪑","I sit in the dental chair","The chair may move backward. I can ask what is happening before we start."],
["😮","I open my mouth","The dental team may look at and clean my teeth. I may hear sounds, see a bright light, or feel tools touching my teeth."],
["✋","I can communicate","I can use words, gestures, pictures, or another communication method to say I need help or a break."],
["⭐","I finish the visit","When the visit is finished, I can leave. I did something new or practiced something important."]
]:genericSteps(data.type);
const firstThen=isDentist?"FIRST: Dental visit  →  THEN: "+esc(shortHelp(data.helps)||"a preferred activity"):"FIRST: "+esc(data.type)+"  →  THEN: "+esc(shortHelp(data.helps)||"a preferred activity");
form.innerHTML='<div class="question pack-screen"><span class="badge">'+esc(data.type)+' READY PACK</span><h2>'+n+'\'s Ready Pack</h2><p>Review this together before the experience. You can print it or save it as a PDF.</p><div class="pack-toolbar"><button class="primary" data-print>Print / Save PDF</button><button class="secondary" data-back>← Edit answers</button></div><div class="ready-pack" id="readyPack"><div class="pack-cover"><div class="pack-mark">Autism<span>Ready</span></div><div class="pack-icon">'+(isDentist?"🦷":"✨")+'</div><h1>'+n+'\'s '+esc(data.type)+' Ready Pack</h1><p>Here is what I can expect.</p><small>'+esc(data.when||"My upcoming experience")+'</small></div><section class="pack-section"><h3>My plan</h3><div class="visual-steps">'+steps.map((s,i)=>'<article><div class="step-icon">'+s[0]+'</div><div><b>'+(i+1)+'. '+s[1]+'</b><p>'+s[2]+'</p></div></article>').join("")+'</div></section><section class="pack-section"><h3>What I know about this visit</h3><p>'+esc(data.details||"This is an upcoming "+data.type.toLowerCase()+" experience.")+'</p></section><section class="pack-section two-col"><div><h3>Things I may notice</h3><p>'+esc(data.sensory||defaultSensory(data.type))+'</p></div><div><h3>Things that may help me</h3><p>'+esc(data.helps||"A clear explanation, time to process, choices when possible, and knowing what happens next.")+'</p></div></section><section class="first-then"><span>MY FIRST / THEN</span><strong>'+firstThen+'</strong></section><section class="pack-section"><h3>My communication reminders</h3><div class="communication"><span>✋ I need a break.</span><span>❓ What happens next?</span><span>🔉 It is too loud.</span><span>✅ I am ready.</span></div></section><section class="caregiver"><h3>For the person supporting me</h3><p>Review the sequence ahead of time. Use clear, concrete language and allow processing time. Bring familiar supports when appropriate. Share relevant preferences with the location before the visit when helpful.</p><p><strong>Remember:</strong> This pack is a preparation tool, not a treatment plan. Adapt it to the individual's communication and support needs.</p></section><div class="pack-footer">Created with AutismReady • Personalized preparation for everyday experiences</div></div></div>';bind();form.querySelector("[data-print]").addEventListener("click",()=>window.print())}
function genericSteps(type){return [["🏠","I get ready","I can look at my plan and bring things that help me."],["🚗","I travel there","I go to my "+type.toLowerCase()+" experience."],["👋","I arrive","I may meet new people and see a new place."],["👀","I notice what is around me","There may be different sounds, sights, smells, or people."],["✋","I can communicate","I can ask a question, request help, or tell someone I need a break."],["⭐","I finish","When the experience is over, I can leave and continue with my day."]]}
function defaultSensory(type){return type==="Dentist"?"Bright lights, dental tools, new sounds, tastes, smells, and people working near the mouth.":"New sounds, sights, smells, people, waiting, and changes in routine."}
function shortHelp(s){if(!s)return"";return s.split(/[,.]/)[0].trim().slice(0,55)}
function bind(){form.querySelectorAll("[data-key]").forEach(el=>el.addEventListener("input",e=>data[e.target.dataset.key]=e.target.value));form.querySelector("[data-next]")?.addEventListener("click",()=>{step++;render()});form.querySelector("[data-back]")?.addEventListener("click",()=>{step--;render()})}
function esc(s){return String(s||"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[m]))}
document.querySelectorAll(".experience").forEach(b=>b.addEventListener("click",()=>openBuilder(b.dataset.type)));document.querySelectorAll("[data-start]").forEach(b=>b.addEventListener("click",()=>document.querySelector("#builder").scrollIntoView({behavior:"smooth"})));document.querySelector(".close").addEventListener("click",()=>modal.classList.remove("open"));modal.addEventListener("click",e=>{if(e.target===modal)modal.classList.remove("open")});