(function(){
var modal=document.getElementById("modal"),form=document.getElementById("form"),bar=document.getElementById("bar"),state={},step=0;
var catalog={
"Dentist":{icon:"🦷",place:"dentist",steps:[["🚗","Travel to the dentist"],["🏢","Arrive and check in"],["⏳","Wait for my turn"],["👋","Meet the dental team"],["🪑","Sit in the dental chair"],["💡","See the bright light"],["😮","Let the team look at my teeth"],["⭐","Finish and leave"]],notices:["Bright lights","Tool sounds","Things near my mouth","New tastes or smells","Waiting"]},
"Doctor":{icon:"🩺",place:"doctor's office",steps:[["🚗","Travel to the office"],["🏢","Check in"],["⏳","Wait for my turn"],["👋","Meet the care team"],["⚖️","Complete routine checks"],["🗣️","Talk about why I am there"],["✋","Ask for help or a break"],["⭐","Finish and leave"]],notices:["Waiting","New people","Touch","Medical equipment","Questions"]},
"Haircut":{icon:"✂️",place:"haircut",steps:[["🚗","Travel to my haircut"],["👋","Meet the stylist or barber"],["🪑","Sit in the chair"],["🧥","Wear a cape if needed"],["💇","Have my hair cut"],["🧹","Notice loose hair"],["🪞","Look at my haircut"],["⭐","Finish and leave"]],notices:["Clippers","Scissors","Hair touching my skin","Cape around my neck","Mirror"]},
"Airplane":{icon:"✈️",place:"airport",steps:[["🧳","Pack what I need"],["🚗","Travel to the airport"],["🎫","Check in"],["🛡️","Go through security"],["⏳","Wait at the gate"],["✈️","Get on the airplane"],["💺","Sit during the flight"],["🛬","Land and get off"]],notices:["Crowds","Announcements","Security","Waiting","Engine noise"]},
"First Day of School":{icon:"🎒",place:"school",steps:[["🌅","Get ready for school"],["🚗","Travel to school"],["🏫","Enter the building"],["👋","Meet adults and classmates"],["🪑","Find my classroom"],["📚","Follow the class plan"],["🍎","Take breaks and eat when scheduled"],["🏠","Go home when school ends"]],notices:["New people","Bell sounds","Busy hallways","New routines","Classroom noise"]},
"Restaurant":{icon:"🍽️",place:"restaurant",steps:[["🚗","Travel to the restaurant"],["👋","Enter and greet the host"],["🪑","Sit at a table"],["📖","Look at choices"],["🗣️","Order food"],["⏳","Wait for food"],["🍽️","Eat or interact at the table"],["⭐","Finish and leave"]],notices:["Food smells","People talking","Waiting","Dishes and kitchen sounds","New foods"]},
"Grocery Store":{icon:"🛒",place:"store",steps:[["📝","Get ready to shop"],["🚗","Travel to the store"],["🛒","Get a cart or basket"],["🥫","Find the items we need"],["👥","Move around other shoppers"],["⏳","Wait at checkout"],["💳","Pay for the items"],["🏠","Leave the store"]],notices:["Crowds","Bright lights","Announcements","Waiting","Many choices"]},
"Birthday Party":{icon:"🎈",place:"party",steps:[["🎁","Get ready for the party"],["🚗","Travel there"],["👋","Arrive and greet people"],["🎵","Notice party sounds"],["🎲","Choose whether to join activities"],["🎂","Cake or food may be served"],["✋","Take a break if needed"],["🏠","Say goodbye and leave"]],notices:["Music","Groups of people","Games","Food","Unexpected changes"]},
"Custom":{icon:"✨",place:"experience",steps:[["🏠","Get ready"],["🚗","Travel or transition"],["👋","Arrive"],["👀","Look at what is happening"],["➡️","Follow the next step"],["✋","Communicate what I need"],["✅","Complete the experience"],["⭐","Finish"]],notices:["New people","New sounds","Waiting","Changes in routine","Unfamiliar places"]}
};
var stages=["person","details","needs","story","preview"];
function esc(v){return String(v||"").replace(/[&<>"']/g,function(m){return{"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[m]})}
function checked(arr,v){return (arr||[]).indexOf(v)>-1?"checked":""}
function open(type){state={type:type,supports:[],notices:[]};step=0;modal.classList.add("open");modal.setAttribute("aria-hidden","false");render()}
function field(label,key,ph){return '<label>'+label+'</label><input data-key="'+key+'" value="'+esc(state[key])+'" placeholder="'+ph+'">'}
function area(label,key,ph){return '<label>'+label+'</label><textarea data-key="'+key+'" placeholder="'+ph+'">'+esc(state[key])+'</textarea>'}
function chips(title,key,items){return '<fieldset><legend>'+title+'</legend><div class="chip-grid">'+items.map(function(v){return '<label class="chip"><input type="checkbox" data-list="'+key+'" value="'+esc(v)+'" '+checked(state[key],v)+'><span>'+v+'</span></label>'}).join("")+'</div></fieldset>'}
function buttons(back,next){return '<div class="form-actions">'+(back?'<button class="secondary" data-back>← Back</button>':'<span></span>')+'<button class="primary" data-next>'+next+' →</button></div>'}
function render(){bar.style.width=((step+1)/stages.length*100)+"%";var type=state.type,c=catalog[type]||catalog.Custom,body="";
if(step===0){body='<span class="badge">'+esc(type)+'</span><h2>Who is this for?</h2><p>Use a first name or nickname. Age helps us keep the language appropriate.</p>'+field("First name or nickname","name","Alex")+field("Age (optional)","age","8")+(type==="Custom"?field("What are we getting ready for?","customType","Example: going to a wedding"):"")+buttons(false,"Continue")}
if(step===1){body='<span class="badge">THE EXPERIENCE</span><h2>What will happen?</h2><p>Add what you know. The pack will still work if plans are uncertain.</p>'+field("When is it happening?","when","Saturday morning")+area("What do you already know?","details","Where you are going, who may be there, or anything important about the plan.")+buttons(true,"Personalize supports")}
if(step===2){body='<span class="badge">SUPPORTS</span><h2>What should the pack prepare for?</h2><p>Select anything that may matter. You can choose several.</p>'+chips("Things they may notice or find difficult","notices",c.notices.concat(["Transitions","Uncertainty","Touch","Strong smells"]))+chips("Supports that may help","supports",["Headphones","Visual schedule","Countdown","First / Then","Breaks","Choice of two options","Comfort item","Short directions","Extra processing time","Reward or preferred activity"])+area("Anything else that helps?","helps","Example: Tell them before touching, let them hold a comfort item, give a 5-minute warning.")+buttons(true,"Build the story")}
if(step===3){body='<span class="badge">STORY BUILDER</span><h2>How should the story feel?</h2><p>Choose the style that best fits the person.</p><label>Story voice</label><select data-key="voice"><option>Simple first-person — “I will…”</option><option>Reassuring first-person</option><option>Simple third-person</option><option>Very short / low language</option></select><label>Story length</label><select data-key="length"><option>Standard — 8 steps</option><option>Short — 6 steps</option><option>Detailed — 10 steps</option></select>'+area("Main goal for this story","goal","Example: Know what will happen and how to ask for a break.")+field("What can happen after? (First / Then)","then","Example: listen to music in the car")+buttons(true,"Create my Ready Pack")}
if(step===4){renderPack();return}
form.innerHTML='<div class="question">'+body+'</div>';bind()}
function bind(){var els=form.querySelectorAll("[data-key]");for(var i=0;i<els.length;i++)els[i].oninput=function(){state[this.getAttribute("data-key")]=this.value};var boxes=form.querySelectorAll("[data-list]");for(var j=0;j<boxes.length;j++)boxes[j].onchange=function(){var k=this.getAttribute("data-list");state[k]=state[k]||[];if(this.checked){if(state[k].indexOf(this.value)<0)state[k].push(this.value)}else state[k]=state[k].filter(function(x){return x!==this.value}.bind(this))};var n=form.querySelector("[data-next]"),b=form.querySelector("[data-back]");if(n)n.onclick=function(){step++;render()};if(b)b.onclick=function(){step--;render()}}
function storyLine(title,i,name,voice){var lead=voice&&voice.indexOf("third-person")>-1?name+" can ":"I can ";var low=voice&&voice.indexOf("low language")>-1;var lines=["get ready for what comes next.","go to the place with my support person.","arrive and look around.","take my time while I learn what happens next.","follow the plan one step at a time.","communicate if I need help, more time, or a break.","use supports that help me feel prepared.","finish the experience and move on to what comes next."];return low?title+".":lead+lines[Math.min(i,lines.length-1)]}
function renderPack(){var c=catalog[state.type]||catalog.Custom,name=esc(state.name||"My"),displayType=state.type==="Custom"?(state.customType||"My Experience"):state.type,voice=state.voice||"Simple first-person — “I will…”",steps=c.steps.slice();if((state.length||"").indexOf("Short")===0)steps=steps.slice(0,6);var previewCount=Math.max(1,Math.ceil(steps.length*0.20));var previewSteps=steps.slice(0,previewCount);var then=state.then||"a preferred activity";var goal=state.goal||"Know what will happen and how to communicate what I need.";
form.innerHTML='<div class="question pack-screen"><span class="badge">PERSONALIZED PREVIEW</span><h2>'+name+'’s '+esc(displayType)+' Ready Pack</h2><p>Your pack has been personalized. Here is a sample before checkout.</p><div class="pack-toolbar"><button class="secondary" data-back>← Edit story</button><button class="secondary" data-new>Build another</button></div><div class="ready-pack preview-pack"><div class="pack-cover"><div class="pack-mark">Autism<span>Ready</span></div><div class="pack-icon">'+c.icon+'</div><h1>'+name+'’s '+esc(displayType)+' Ready Pack</h1><p>Here is what I can expect and what can help me.</p><small>'+esc(state.when||"My upcoming experience")+'</small></div><section class="pack-section story"><div class="section-label">PREVIEW • 20% OF YOUR STORY</div><h3>I can get ready for '+esc(displayType).toLowerCase()+'.</h3><p class="goal"><strong>My goal:</strong> '+esc(goal)+'</p><div class="visual-steps">'+previewSteps.map(function(s,i){return '<article><div class="step-icon">'+s[0]+'</div><div><b>'+(i+1)+'. '+s[1]+'</b><p>'+esc(storyLine(s[1],i,state.name||"They",voice))+'</p></div></article>'}).join("")+'</div></section><section class="locked-product"><div class="lock-icon">🔒</div><h3>Your complete Ready Pack is ready</h3><p>Unlock the remaining story steps plus the visual schedule, personalized sensory supports, First / Then card, communication cards, caregiver guide, and printable PDF.</p><div class="locked-list"><span>🔒 Full personalized story</span><span>🔒 Visual schedule</span><span>🔒 Sensory preparation</span><span>🔒 First / Then support</span><span>🔒 Communication cards</span><span>🔒 Caregiver guide</span><span>🔒 Print / Save PDF</span></div><div class="unlock-price">$7.99 <small>one-time</small></div><button class="primary unlock-btn" data-unlock>Unlock my complete Ready Pack →</button><small class="secure-note">Checkout is being connected. No payment will be collected from this preview build.</small></section></div></div>';
var b=form.querySelector("[data-back]"),nw=form.querySelector("[data-new]"),u=form.querySelector("[data-unlock]");if(b)b.onclick=function(){step=3;render()};if(nw)nw.onclick=function(){modal.classList.remove("open");document.getElementById("builder").scrollIntoView({behavior:"smooth"})};if(u)u.onclick=function(){u.textContent="Checkout coming next";u.disabled=true;var note=form.querySelector(".secure-note");if(note)note.textContent="Your complete pack stays locked until a successful payment is confirmed."}}
var experiences=document.querySelectorAll(".experience");for(var i=0;i<experiences.length;i++)experiences[i].onclick=function(){open(this.getAttribute("data-type"))};var starts=document.querySelectorAll("[data-start]");for(var j=0;j<starts.length;j++)starts[j].onclick=function(){document.getElementById("builder").scrollIntoView({behavior:"smooth"})};var close=document.querySelector(".close");if(close)close.onclick=function(){modal.classList.remove("open")};if(modal)modal.onclick=function(e){if(e.target===modal)modal.classList.remove("open")};
})();